name: auto approve pullrequest 

on:
  pull_request:
    branches:
      - 'feature/**'
jobs:
  approve_merge:
    if:  startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --merge